### ISSUE TITLE
Create README.md and CONTRIBUTING.md files

### ISSUE THREAD

**Issue by Loknar** [gasvaktin/gasvaktin.github.io#22]
I believe this site might benefit from others than myself contributing to it as I'm not incredibly sawy in front-end coding..

With this in mind, creating a README and [CONTRIBUTING (contributing guidelines file)](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) markdown files might prove very helpful for newcomers to be able to quickly know what's up and how to get started contributing.

**Comment by JrPribs** [comment]
I'll work on this now. Let me know if there is anything specific I should include in the files.
