### ISSUE TITLE
Gasvaktin.js operations flow lacking.

### ISSUE THREAD

**Issue by Loknar** [gasvaktin/gasvaktin.github.io#23]
There are race conditions and ugly code to cover some of them, needs to be cleaned up. I think it would be cool to rewrite using Promises ...

How to reproduce:
- reload the page until it happens :-1: 

![alt text](http://i.imgur.com/oa1r13n.png)

**Comment by shinning91** [comment]
Hey can I try on this issue?

**Comment by Loknar** [comment]
Promisified flow control in https://github.com/gasvaktin/gasvaktin.github.io/pull/31
