### ISSUE TITLE
Current petrol type UI switch not browser/mobile friendly enough.

### ISSUE THREAD

**Issue by Loknar** [gasvaktin/gasvaktin.github.io#24]
Also it uses great bunch of jQuery ... I know I'm using Twitter Bootstrap for great deal of things and jQuery is necessary because of that, but I would like to keep jQuery usage low, and this switch needs improvements regardless of jQuery.

**Comment by sasikadesilva** [comment]
this is good project. i like it and i like to joint with this project. i have good knowledge about twitter bootstrap and jQuery. and i'am worcking with front end developing.

**Comment by armudgal** [comment]
I found it mobile friendly, can you be more specific.

**Comment by Loknar** [comment]
this issue was resolved with new switch buttons in https://github.com/gasvaktin/gasvaktin.github.io/pull/39
forgot to close this issue, closing it now
