### ISSUE TITLE
Create page that shows info on recent/all price changes since the project started.

### ISSUE THREAD

**Issue by Loknar** [gasvaktin/gasvaktin.github.io#25]
The data will be available [here](https://github.com/gasvaktin/gasvaktin.github.io/blob/master/data/price_changes.json) (https://raw.githubusercontent.com/gasvaktin/gasvaktin.github.io/master/data/price_changes.json), I plan to setup automated commit bot to update this file when new price changes happen ...

**Comment by klazich** [comment]
Hey @Loknar, mind if I take a look at this?

**Comment by Loknar** [comment]
made some chart groundwork, see https://github.com/gasvaktin/gasvaktin.github.io/pull/37 and https://gasvaktin.is/punctuality.html

**Comment by Loknar** [comment]
finished quite some time ago, see https://gasvaktin.is/trends/
closing
