### ISSUE TITLE
Rework color scheme of the site

### ISSUE THREAD

**Issue by Loknar** [gasvaktin/gasvaktin.github.io#26]
Current color scheme a bit too plain white, however plain can also be good :smiling_imp: 

I'm kinda fond of building the color scheme around this #483D8B purple color ... but other suggestions welcome.

**Comment by orgh0** [comment]
i'll work on it. i am a begginner. and might need some help

**Comment by orgh0** [comment]
done . :)

**Comment by Loknar** [comment]
That was quick O.o

Do you have pull request with changes?

**Comment by orgh0** [comment]
yes.

**Comment by orgh0** [comment]
already pulled a request

**Comment by JrPribs** [comment]
I see the existing PR only changed the background color. I would be interested in taking the color changes further. Please let me know if that PR will be merged and satisfies the issue, or If I should move forward with reworking styles a bit further than just the background.

**Comment by luongthomas** [comment]
I would like to help out but I am unsure of how to get the repository to start.  I've installed dependencies with npm and tried to run with npm start but to no avail.

**Comment by axelg12** [comment]
@luongthomas I've updated the README with more detailed information. You need to run node server.js to get it started

**Comment by luongthomas** [comment]
[On this site](http://paletton.com/#uid=1470u0kkDpaaFD6g2tUoplgtmgi), if you click examples at the bottom leftish, you can see a sample site with the color scheme around the desired color.  Could you point me to which one looks best?  There are four sample page layouts: white page, dark page, positive design or negative design.  

I'll get started as soon as I get a better idea of which color scheme is desired.

**Comment by Loknar** [comment]
Colorscheme rework for https://gasvaktin.is/ has been made.
Similar rework for https://gasvaktin.is/trends/ is unfinished.

**Comment by armudgal** [comment]
The petrol tab should be reworked for  https://gasvaktin.is/trends/ right?
